Repository DavviSantos/HangmanGame, pull requests merged in 2024-10, with the labels that each got.

#6 Criação de Entity Jogador
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/jogador/Jogador.java
Labels: enhancement

#9 feat: Adiciona boneco do jogo
  HangmanGame/bin/main/java/br/edu/iff/jogoforca/dominio/boneco/texto/.gitkeep
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/boneco/Boneco.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/boneco/BonecoFactory.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/boneco/texto/.gitkeep
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/boneco/texto/BonecoTexto.java
Labels: enhancement

#11 Criar Tema
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/tema/Tema.java
Labels: enhancement

#13 Criar jogador repository
  HangmanGame/bin/main/java/br/edu/iff/jogoforca/dominio/jogador/embdr/.gitkeep
  HangmanGame/bin/main/java/br/edu/iff/jogoforca/dominio/jogador/emmemoria/.gitkeep
  HangmanGame/bin/resources/database.properties
  HangmanGame/src/main/java/br/edu/iff/config/DatabaseConnectionFactory.java
  HangmanGame/src/main/java/br/edu/iff/dominio/ObjetoDominioImpl.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/jogador/JogadorRepository.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/jogador/embdr/.gitkeep
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/jogador/embdr/BDRJogadorRepository.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/jogador/emmemoria/.gitkeep
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/jogador/emmemoria/MemoriaJogadorRepository.java
  HangmanGame/src/resources/database.properties
Labels: enhancement

#16 Atualiza branch criar palavra
  HangmanGame/bin/main/java/br/edu/iff/jogoforca/dominio/jogador/embdr/.gitkeep
  HangmanGame/bin/main/java/br/edu/iff/jogoforca/dominio/jogador/emmemoria/.gitkeep
  HangmanGame/bin/resources/database.properties
  HangmanGame/src/main/java/br/edu/iff/config/DatabaseConnectionFactory.java
  HangmanGame/src/main/java/br/edu/iff/dominio/ObjetoDominioImpl.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/jogador/JogadorRepository.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/jogador/embdr/.gitkeep
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/jogador/embdr/BDRJogadorRepository.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/jogador/emmemoria/.gitkeep
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/jogador/emmemoria/MemoriaJogadorRepository.java
  HangmanGame/src/resources/database.properties
Labels: invalid

#20 12 criar palavra
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/palavra/Palavra.java
Labels: enhancement

#19 Criar tema repository
  HangmanGame/.vscode/settings.json
  HangmanGame/bin/main/java/br/edu/iff/bancodepalavras/dominio/tema/embdr/.gitkeep
  HangmanGame/bin/main/java/br/edu/iff/bancodepalavras/dominio/tema/emmemoria/.gitkeep
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/tema/Tema.java
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/tema/TemaRepository.java
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/tema/embdr/.gitkeep
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/tema/embdr/BDRTemaRepository.java
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/tema/emmemoria/.gitkeep
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/tema/emmemoria/MemoriaTemaRepository.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/jogador/Jogador.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/jogador/embdr/BDRJogadorRepository.java
Labels: enhancement

#24 Teste
  HangmanGame/README.md
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/palavra/Palavra.java
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/palavra/PalavraFactory.java
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/palavra/PalavraFactoryImpl.java
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/palavra/PalavraRepository.java
Labels: bug

#25 fix: Soluciona problema ocasionado pelo merge
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/palavra/Palavra.java
Labels: bug

#29 feat: Adiciona TemaFactory com erro handler
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/tema/TemaFactory.java
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/tema/TemaFactoryImpl.java
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/tema/TemaInstanceException.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/rodada/Rodada.java
Labels: enhancement

#30 Criar fabricas boneco letra
  HangmanGame/bin/main/java/br/edu/iff/jogoforca/dominio/boneco/imagem/.gitkeep
  HangmanGame/bin/main/java/br/edu/iff/jogoforca/imagem/.gitkeep
  HangmanGame/bin/main/java/br/edu/iff/jogoforca/texto/.gitkeep
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/letra/LetraFactoryImpl.java
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/letra/imagem/LetraImagemFactory.java
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/letra/texto/LetraTextoFactory.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/ElementoGraficoFactory.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/boneco/imagem/.gitkeep
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/boneco/imagem/BonecoImagem.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/boneco/imagem/BonecoImagemFactory.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/boneco/texto/BonecoTextoFactory.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/imagem/.gitkeep
  HangmanGame/src/main/java/br/edu/iff/jogoforca/imagem/ElementoGraficoImagemFactory.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/texto/.gitkeep
  HangmanGame/src/main/java/br/edu/iff/jogoforca/texto/ElementoGraficoTextoFactory.java
Labels: enhancement

#35 feat: Adiciona JogadorFactory
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/jogador/JogadorFactory.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/jogador/JogadorFactoryImpl.java
Labels: enhancement

#37 14 criar rodada
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/rodada/Rodada.java
Labels: enhancement

#36 criar palavra bdr e emmemoria
  HangmanGame/bin/main/java/br/edu/iff/bancodepalavras/dominio/palavra/embdr/.gitkeep
  HangmanGame/bin/main/java/br/edu/iff/bancodepalavras/dominio/palavra/emmemoria/.gitkeep
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/palavra/Palavra.java
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/palavra/embdr/.gitkeep
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/palavra/embdr/BDRPalavraRepository.java
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/palavra/emmemoria/.gitkeep
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/palavra/emmemoria/MemoriaPalavraRepository.java
Labels: enhancement

#38 35 criar rodada factory e repository
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/rodada/RodadaFactory.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/rodada/RodadaFactoryImpl.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/rodada/RodadaRepository.java
Labels: enhancement

#40 fix: Resolve alguns problemas da classe Rodada
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/rodada/Rodada.java
Labels: bug

#41 criação de PalavraAppService
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/palavra/PalavraAppService.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/rodada/Item.java
Labels: enhancement

#43 feat: Adiciona RodadaAppService
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/jogador/JogadorNaoEncontradoException.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/rodada/RodadaAppService.java
Labels: enhancement

#45 feat: criação de Memoria-Rodada-Repository
  HangmanGame/bin/main/java/br/edu/iff/jogoforca/dominio/rodada/emmemoria/.gitkeep
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/rodada/emmemoria/.gitkeep
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/rodada/emmemoria/MemoriaRodadaRepository.java
Labels: enhancement

#46 46 criar repository factory
  HangmanGame/src/main/java/br/edu/iff/jogoforca/RepositoryFactory.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/emmemoria/.gitkeep
  HangmanGame/src/main/java/br/edu/iff/jogoforca/emmemoria/MemoriaRepositoryFactory.java
Labels: enhancement

#44 44 criar rodada sorteio factory
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/rodada/sorteio/.gitkeep
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/rodada/sorteio/RodadaSorteioFactory.java
Labels: enhancement

#47 Criação da parametrized factory aplicação
  HangmanGame/bin/main/java/br/edu/iff/jogoforca/dominio/rodada/embdr/.gitkeep
  HangmanGame/bin/main/java/br/edu/iff/jogoforca/dominio/rodada/sorteio/.gitkeep
  HangmanGame/bin/main/java/br/edu/iff/jogoforca/embdr/.gitkeep
  HangmanGame/bin/main/java/br/edu/iff/jogoforca/emmemoria/.gitkeep
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/tema/TemaFactoryImpl.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/Aplicacao.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/embdr/.gitkeep
  HangmanGame/src/main/java/br/edu/iff/jogoforca/embdr/BDRRepositoryFactory.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/imagem/ElementoGraficoImagemFactory.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/texto/ElementoGraficoTextoFactory.java
Labels: enhancement

#49 Update TemaFactoryImpl.java
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/tema/TemaFactoryImpl.java
Labels: enhancement

#48 Update RodadaAppService.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/rodada/RodadaAppService.java
Labels: enhancement

#51 Criacao app
  HangmanGame/bin/main/java/br/edu/iff/jogoforca/dominio/rodada/embdr/.gitkeep
  HangmanGame/src/App.java
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/letra/texto/LetraTexto.java
  HangmanGame/src/main/java/br/edu/iff/bancodepalavras/dominio/palavra/Palavra.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/rodada/Item.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/rodada/Rodada.java
  HangmanGame/src/main/java/br/edu/iff/jogoforca/dominio/rodada/sorteio/RodadaSorteioFactory.java
Labels: enhancement
